### ISSUE TITLE
Experiencing a double canvas creation on initialisation

### ISSUE THREAD

**Issue by Allerion** [kemayo/maphilight#38]
Not sure if this is due to my coding or a bug in the plugin. Has anyone else experienced this?

When I run .maphilight on a DOM element, I get 2 canvas elements created instead of just one.

If I then rerun .maphilight on the same DOM element updates affect the second canvas element, the first remains unchanged.

The DOM element I'm working with comes in via Ajax, but the plugin doesn't generally have a problem with that.

Anyone else come across this?

**Comment by kemayo** [comment]
There should indeed be two canvases... if you have an `alwaysOn` area.
