### ISSUE TITLE
Resized images are shown in full size

### ISSUE THREAD

**Issue by SimonSimCity** [kemayo/maphilight#53]
As the javascript currently adds the image as background-image of a DIV tag, the image is shown in it's full size. This get's quite uncomfortable if you're working with 2x images or have your images resized because of a lower screen-resolution.

The solution here is to add the css `.attachment-original { background-size: contain; }`, what is ignored (at least in Firefox) if you add it it your css file, because the system already adds a `background` property here.

My solution:
- Updated line 247 to set the background as CSS-property `backgroundImage` not as `background` to allow me to overwrite only some of the background-settings
- Add `.attachment-original { background-size: contain; }` to my css file.

Please update in line 247 or write another proposal here.

**Comment by MrCsabaToth** [comment]
"background-repeat":'no-repeat' is needed too

**Comment by MrCsabaToth** [comment]
Although the image height still stuck fixed. Needs a little more work.

**Comment by ricardomcardoso** [comment]
> "background-repeat":'no-repeat' is needed too

I need to add this property, they want me to open a branch and commit?
