### ISSUE TITLE
Events not unbound, when using a different map name/id resulting in memory leak

### ISSUE THREAD

**Issue by herbalite** [kemayo/maphilight#55]
I'm dynamically replacing images.

They will have their own usemap name. 

This means old usemap events never get released, as the current code just takes the usemap name as a reference for releasing them. Probabally needs a slightly different event binding mechanism.

**Comment by kemayo** [comment]
There's not any incredibly good ways to notice when you're removing stuff from the DOM. I'm inclined to say that you should just call `$(map_node).unbind('.maphilight')` yourself if you're doing that.
