### ISSUE TITLE
How to make it responsive?

### ISSUE THREAD

**Issue by nosov33** [kemayo/maphilight#57]
How to make it responsive and save hightlight effect? Thank you!

**Comment by econolution** [comment]
Check out our solution for both http://www.townlife.com/world/Canada/Alberta/Pigeon%20Lake/415/Fun-Map

**Comment by nosov33** [comment]
Thank you very much @econolution! Now I understand!

**Comment by gpstiip88** [comment]
The link not works. Can you help me?
