### ISSUE TITLE
Changing colors dynamically

### ISSUE THREAD

**Issue by lacroixdavid1** [kemayo/maphilight#58]
I am trying to change colors of maphilight dynamically.

 reponse = JSON.parse(reponse);

            $('area').each(function()  {
                $(this).attr('data-maphilight', '{"stroke":0, "fillColor":"CCFFCC", "fillOpacity":0.3, "alwaysOn":true}');
            })  

            for (var i = 0; reponse.length > i; i++) {
                var test = '#'.concat(reponse[i].nomTerrain);
                $(test).attr('data-maphilight', '{"stroke":0, "fillColor":"FF0000", "fillOpacity":0.3, "alwaysOn":true}');
            }

            $('img[usemap]').maphilight();

This works only once. When it comes to a second time, it doesn't ! It changes CSS classes, but not the maphilight! pls help me !!

**Comment by akshaykamble** [comment]
Hi lacroixdavid1,
Did you get any workaround for this issue?

**Comment by lacroixdavid1** [comment]
Yes it it is working now. Instead of using .attr() i use .data() to change
options on the fly
