### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by thecheshirecat** [kemayo/maphilight#69]
Hi,

I've downloaded the plugin, and tried to do a simple map, but they don't high light.

Demo: https://jsfiddle.net/hnjqf1n2/2/

Something wrong within it?

**Comment by kemayo** [comment]
The error it has in the console is `Uncaught TypeError: $(...).maphilight is not a function`

Thus: you're not using the right URL for the maphilight JS file. You're just linking to the page on github, which isn't going to work. You'd have a better time if you used something like `https://rawgit.com/kemayo/maphilight/master/jquery.maphilight.min.js`

**Comment by thecheshirecat** [comment]
Ok, but in my pc I download it, no errors are given and it doesnt highlight, with that exact code

**Comment by kemayo** [comment]
Well, here, version of the fiddle using that URL instead: https://jsfiddle.net/urfp7asv/

It works.
