### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by SimonMARTIN87** [kemayo/maphilight#78]
cdnjs releases are outdated.
Please release the jquery 3 compatible version.

Btw, this is a very nice plugin. 👍

**Comment by TylerRick** [comment]
Just ran into this myself.

It says
```Uncaught TypeError: map.size is not a function```
because size() was removed from jQuery 3.

**Comment by TylerRick** [comment]
Ah, so https://github.com/kemayo/maphilight/pull/70 was merged in but no new release has been made yet?

**Comment by TylerRick** [comment]
Using https://rawcdn.githack.com/kemayo/maphilight/7932449fbc49c7767fbd72a807110c632c11ee95/jquery.maphilight.js as a workaround for now

**Comment by kemayo** [comment]
Done. 1.4.0 is released.
