### ISSUE TITLE
demo_usa.png - straight line

### ISSUE THREAD

**Issue by madhuatit** [kemayo/maphilight#81]
there is a straight line on the map image over the states - lowa/illinois/indiana/ohio. could you let me know if its an issue on map or something that i am wrong.

**Comment by kemayo** [comment]
That's actually in the image. I think at the time I generated the map, it was an unavoidable export artifact. That said... it's been a decade, so I think I can probably do better now.

**Comment by madhuatit** [comment]
Thanks Kemayo, could you pls upload a better map for the same, that would be helpful for me.

**Comment by kemayo** [comment]
Sure, 438c793e06387b96ea6afa1466c9eeccf9221b51 includes it.
