### ISSUE TITLE
Not highligh on the multiple imges i.e. multiple ploygons there should be some orders of ploygons 

### ISSUE THREAD

**Issue by alicerommi** [kemayo/maphilight#83]
I have 27+ images which are showing in the document but this lib does'nt work on multiple images in my case
Can you please tell me how i will set the orders of ploygons or images.

**Comment by this-shivi** [comment]
Do you mean to say that you want to highlight multiple polygons?

I took random ids of polygons and put the _hilight code_ (that I found somewhere on the internet) in interval of _3 seconds_.
```
setInterval(function(){
 data = $('#id').data('maphilight') || {};
 data.alwaysOn = !data.alwaysOn;
 $('#id').data('maphilight',data).trigger('alwaysOn.maphilight');
}, 3000);
```
This can be modified as per your requirements.

**Comment by alicerommi** [comment]
the issue has been fixed.
