### ISSUE TITLE
Looping through map areas before initiating maphilight changes result

### ISSUE THREAD

**Issue by TheBigFatTony** [kemayo/maphilight#90]
This is the key code:
```
    for (var i = 0; i < map_data.children.length; i++) {
        var area = map_data.children[i];
        // if (area.shape = "circle") {
        //     console.log("circle")
        // }
    }

    $('#kegg_map').maphilight({alwaysOn: true})
```
This produces what you can see on the left side of the image below.
However, when I uncomment the lines, I get what is on the right side.
What went wrong?

![image](https://user-images.githubusercontent.com/24833908/62621443-25729580-b91c-11e9-8c89-a7c3eca42d52.png)

[Here, you can download the full code.
](https://campuscloud.unibe.ch:443/ssf/s/readFile/share/30994/-6372221393134272211/publicLink/html.zip)

PS: My goal is to turn specific boxes on/off using Javascript.
PPS: Problem occurs in Chrome and Firefox.

**Comment by kemayo** [comment]
This is certainly too late, but: you're assigning in the loop. `if (area.shape = "circle") {` is setting ever `area`'s shape to `circle`.

It should be `if (area.shape == "circle") {`

**Comment by MrTomRod** [comment]
How embarrassing. 😅 Thanks!

**Comment by TheBigFatTony** [comment]
How embarrassing. :sweat_smile: Thanks!
