### ISSUE TITLE
API Docs endpoint is offline

### ISSUE THREAD

**Issue by duckyb** [kemayo/maphilight#99]
Just reporting that the docs endpoint has been unavailable for the past few days (at least!).

## https://davidlynch.org/projects/maphilight/docs/

![img](https://i.imgur.com/kQ2Z5xU.png)

**Comment by kemayo** [comment]
Oh hey, thanks for that. I had to switch hosting providers earlier this month, so I may have broken the redirect then. I've fixed that so it'll go to the appropriate location now, which is: https://projects.davidlynch.org/maphilight/docs/

...I should just get it on to the GitHub project-site hosting, really.
